name: owasp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - npm
  - pip:
      - django==5.1.3
      - python-dotenv
      - safety
      - pytest
      - cryptography
